@urlBase = http://localhost:5000 

### fazer login
# @name postLogin
POST {{urlBase}}/login
Content-Type: application/json

{
    "email": "ana@mail.com.br",
    "senha": "123456"
}

###
@token = {{postLogin.response.body.token}}

###
GET {{urlBase}}/info/atores
Authorization: Bearer {{token}}